apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: {{.Release.Name}}
  namespace: {{.Release.Namespace}}
  labels:
    app.kubernetes.io/name: {{.Release.Name}}
  annotations:
    kubernetes-engine.cloud.google.com/icon: >-
      data:image/png;base64,{{ .Files.Get "logo.png" | b64enc }}
    marketplace.cloud.google.com/deploy-info: '{"partner_id": "checkpoint-public", "product_id": "cpappsec", "partner_name": "Check Point"}'
spec:
  descriptor:
    type: cpappsec
    version: "0.1.148370"
  selector:
    matchLabels:
      app.kubernetes.io/name: {{.Release.Name}}
  addOwnerRef: true
  componentKinds:
  - group: v1
    kind: Secret
  - group: v1
    kind: Service
  - group: v1
    kind: ConfigMap
  - group: v1
    kind: ServiceAccount
  - group: apps
    kind: Deployment
  - group: ''
    kind: Ingress
