# The secrets used when deploying nginx/cpnano.
apiVersion: v1
kind: Secret
metadata:
  name: {{.Release.Name}}-cp-secret
  annotations:
    agentVersion: {{.Chart.Version }}
  labels:
    app.kubernetes.io/name: {{.Release.Name}}-cp-secret
    helm.sh/chart: {{.Chart.Name }}-{{.Chart.Version | replace "+" "_" }}
    app.kubernetes.io/instance: {{.Release.Name | quote }}
type: Opaque
data:
  tls.key: {{.Values.TLS_CERTIFICATE_KEY }}
  tls.crt: {{.Values.TLS_CERTIFICATE_CRT }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{.Release.Name}}-cp-test-secret
  annotations:
    agentVersion: {{.Chart.Version}}
  labels:
    app.kubernetes.io/name: {{.Release.Name}}-cp-test-secret
    helm.sh/chart: {{.Chart.Name }}-{{.Chart.Version | replace "+" "_" }}
    app.kubernetes.io/instance: {{.Release.Name | quote }}
type: Opaque
data:
  tls.key: {{.Values.TLS_CERTIFICATE_KEY }}
  tls.crt: {{.Values.TLS_CERTIFICATE_CRT }}
