# Service configuration for the nginx ingress controller service
# To expose the Ingress controller pods, you can use a different service configuration, according to this guide:
# https://docs.nginx.com/nginx-ingress-controller/installation/installation-with-manifests/
apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-svc
  namespace: {{.Release.Namespace}}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-cp-ingress-ctl-svc
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
  annotations:
    marketplace.cloud.google.com/deploy-info: '{"partner_id": "checkpoint-public", "product_id": "cpappsec", "partner_name": "Check Point"}'
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
    service.beta.kubernetes.io/azure-dns-label-name: {{ .Release.Namespace }} 
spec:
  type: LoadBalancer 
  ports:
  - port: 80
    targetPort: 80
    nodePort: {{.Values.myNodePort}}
    protocol: TCP
    name: http
  - port: 443
    targetPort: 443
    nodePort: {{.Values.mySSLNodePort}}
    protocol: TCP
    name: https
  selector:
    app: nginx-ingress
