properties:
  testerImage:
    type: string
    default: $REGISTRY/tester:$TAG
    x-google-property:
      type: IMAGE
  nanoToken:
    type: string
    default: "cp-ef533049-6e3d-4e79-beaa-599fdb601ca266371efa-c60d-4dfb-a607-4f1100acb9e9"
    description: "Insert your token from CloudGuard AppSec Portal App Token here"
  appURL:
    type: string
    default: "juice-shop.checkpoint.com"
    description: "Your Application URL"
  mysvcname:
    type: string
    default: "juice-shop"
    description: "Your applicaiton service name"
  mysvcport:
    type: string
    default: "8080"
    description: "The service port your application is listening on"

