properties:
  testerImage:
    type: string
    default: $REGISTRY/tester:$TAG
    x-google-property:
      type: IMAGE
  nanoToken:
    type: string
    default: "cp-10823b12-49af-4329-aec9-879d57415c507bcb74c3-1ba7-49bc-963b-1fcddc0c2d60"
    description: "Insert your token from CloudGuard AppSec Portal App Token here"
  appURL:
    type: string
    default: "juice-shop.checkpoint.com"
    description: "Your Application URL"
  mysvcname:
    type: string
    default: "juice-shop"
    description: "Your applicaiton service name"
  mysvcport:
    type: string
    default: "8080"
    description: "The service port your application is listening on"

